apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ywxq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-ywxq@sha256:f1a02dcff65903538862cd9759841a015a99ca628f28ba4405e41689f747f9e5
        name: my-nodejs
        resources: {}
status: {}
